project_id = "ppdsxgkmnmjfwmpnamts"

[functions.goal-reminders]
verify_jwt = false

[functions.review-notification]
verify_jwt = false

[functions.review-acknowledgment-notification]
verify_jwt = false

[functions.leave-status-notification]
verify_jwt = false

[functions.leave-submission-notification]
verify_jwt = false

[functions.onboarding-notification]
verify_jwt = false

[functions.onboarding-reminders]
verify_jwt = false

[functions.event-notification]
verify_jwt = false

[functions.onboarding-request-notification]
verify_jwt = false

[functions.attendance-reminders]
verify_jwt = false

[functions.version-check]
verify_jwt = false

[functions.invite-employee]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-sms]
enabled = true
verify_jwt = false
import_map = "./functions/send-sms/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-sms/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-sms/*.html" ]
